# Generated by Django 3.1.6 on 2021-07-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0010_auto_20210726_1751'),
        ('users', '0005_userbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderbook.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together={('currency', 'user')},
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='currency_name',
        ),
    ]
