# Generated by Django 3.1.6 on 2021-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210726_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_level_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.CharField(max_length=200, unique=True)),
                ('spred', models.CharField(max_length=200, unique=True)),
                ('borrow_interest', models.CharField(max_length=200, unique=True)),
                ('margin_call', models.CharField(max_length=200, unique=True)),
                ('Futures_leverage', models.CharField(max_length=200, unique=True)),
                ('Margin_leverage', models.CharField(max_length=200, unique=True)),
                ('inicial_balance_USDT', models.CharField(max_length=200, unique=True)),
                ('inicial_balance_JILL', models.CharField(max_length=200, unique=True)),
                ('max_withdraw_USDT', models.CharField(max_length=200, unique=True)),
                ('max_withdraw_JILL', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
