# Generated by Django 3.1.6 on 2021-07-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_level_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_level_fields',
            new_name='User_level_field',
        ),
        migrations.RenameField(
            model_name='user_level_field',
            old_name='user_level',
            new_name='level_key',
        ),
    ]
