# Generated by Django 3.1.6 on 2021-07-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210727_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
