# Generated by Django 3.1.6 on 2021-08-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0019_auto_20210803_1928'),
        ('users', '0010_auto_20210729_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userbalance',
            name='balance_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.balancefor'),
        ),
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together={('currency', 'user', 'balance_for')},
        ),
    ]
