# Generated by Django 3.1.6 on 2021-09-11 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210911_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
