# Generated by Django 3.1.6 on 2021-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210918_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jillion_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
