# Generated by Django 3.1.6 on 2021-10-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('active', 'Active')], default='active', max_length=200)),
                ('amount', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.loan'),
        ),
    ]
