# Generated by Django 3.1.6 on 2021-07-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0015_currency_contract_creator_hash'),
        ('IaBotpredict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iabotcontract',
            old_name='contractnumber',
            new_name='contract_number',
        ),
        migrations.AlterField(
            model_name='iabotcontract',
            name='lose_close_point',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iabotcontract',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbook.tradingpair'),
        ),
        migrations.AlterField(
            model_name='iabotcontract',
            name='timeframe',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iabotcontract',
            name='win_close_point',
            field=models.CharField(max_length=200),
        ),
    ]
