# Generated by Django 3.1.6 on 2021-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IaBotpredict', '0002_auto_20210730_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iabotcontract',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], max_length=200),
        ),
    ]
