# Generated by Django 3.1.6 on 2021-07-24 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_sell', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=200)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=36)),
                ('status', models.CharField(choices=[('new', 'New'), ('fill', 'Fill')], max_length=200)),
                ('contract_type', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
