# Generated by Django 3.1.6 on 2021-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contract_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], max_length=200),
        ),
    ]
