# Generated by Django 3.1.6 on 2021-07-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0003_auto_20210724_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
