# Generated by Django 3.1.6 on 2021-07-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0005_tradingpairs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tradingPairs',
            new_name='TradingPair',
        ),
    ]
