# Generated by Django 3.1.6 on 2021-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0006_auto_20210726_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='chain',
            field=models.CharField(default='ERC-20', max_length=10),
        ),
    ]
