# Generated by Django 3.1.6 on 2021-07-26 16:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0008_auto_20210726_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='pair', unique=True),
        ),
    ]
