# Generated by Django 3.1.6 on 2021-07-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0010_auto_20210726_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=18, default=0.005, max_digits=36),
        ),
    ]
