# Generated by Django 3.1.6 on 2021-07-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0013_auto_20210728_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='last_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
