# Generated by Django 3.1.6 on 2021-07-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0015_currency_contract_creator_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermachmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], max_length=200)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbook.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='getexchangepricemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('number_of_candel', models.CharField(max_length=200)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbook.tradingpair')),
            ],
        ),
    ]
