# Generated by Django 3.1.6 on 2021-08-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0016_getexchangepricemodel_ordermachmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getexchangepricemodel',
            name='exchange',
            field=models.CharField(default='Binance', max_length=200),
        ),
        migrations.AlterField(
            model_name='getexchangepricemodel',
            name='number_of_candel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='getexchangepricemodel',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbook.tradingpair', unique=True),
        ),
    ]
