# Generated by Django 3.1.6 on 2021-08-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0017_auto_20210803_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getexchangepricemodel',
            name='pair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderbook.tradingpair'),
        ),
    ]
