# Generated by Django 3.1.6 on 2021-08-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0018_auto_20210803_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('fill', 'Fill'), ('partial_fill', 'Partial_Fill')], default='new', max_length=200),
        ),
    ]
