# Generated by Django 3.1.6 on 2021-09-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0019_auto_20210803_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='last_price',
        ),
        migrations.AddField(
            model_name='currency',
            name='default_public_key',
            field=models.TextField(null=True),
        ),
    ]
