# Generated by Django 3.1.6 on 2021-09-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YeildContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeildpair', models.CharField(max_length=200, unique=True)),
                ('liquidity', models.IntegerField()),
                ('APR', models.DecimalField(decimal_places=2, max_digits=7)),
                ('APYd365', models.CharField(max_length=200)),
                ('d30', models.CharField(max_length=200)),
                ('d7', models.CharField(max_length=200)),
                ('d1', models.CharField(max_length=200)),
            ],
        ),
    ]
