# Generated by Django 3.1.6 on 2021-09-11 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yeildfarming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeildOrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jill_purchase_commission', models.DecimalField(decimal_places=18, default=0.005, max_digits=36)),
                ('Jill_reward', models.DecimalField(decimal_places=18, default=10000, max_digits=36)),
                ('coin_reward', models.DecimalField(decimal_places=18, default=10000, max_digits=36)),
                ('volume', models.DecimalField(decimal_places=18, default=10000, max_digits=36)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('finish', 'Finish')], default='new', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeildfarming.yeildcontract')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
