# Generated by Django 3.1.6 on 2021-09-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210918_1659'),
        ('yeildfarming', '0002_yeildorderbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeildcontract',
            name='required_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userlevel'),
        ),
    ]
